### ISSUE TITLE
Broken Import for ThaumatoAnakalyptor.Random_Walks

### ISSUE THREAD

**Issue by andrewjouffray** [schillij95/ThaumatoAnakalyptor#34]
While running the code I encountered a small issue breaking the UI

In `GUI/MainWindow.py` line 35 the following import `from ThaumatoAnakalyptor.Random_Walks import compute as compute_stitch_sheet` seems to refer to a non existent file. I did find `instances_to_graphs.py` that may seem to have a compute function that matches the functionality of Random_walks but I don't want to start randomly replacing imports without consulting with you first.

**Comment by schillij95** [comment]
Hi Andrew,
You found an outdated part in the UI.
The stitching was recently updated to use the cpp graph_problem solver instead of random walks.
The Readme has not yet been updated too.
Regards, Julian

**Comment by andrewjouffray** [comment]
OK sounds good, I will see if I can replace the calls to `compute_stitch_sheet()` with the graph_problem solver and update the Readme as well.

**Comment by schillij95** [comment]
Amazing, it is a pleasure having you on board!

We did not, I just created a Projects tracker.
Otherwise, we are active on Discord. You can join the Discord community by following the instructions here: https://scrollprize.org/get_started#1-join-the-community
We have an #autosegmentation channel, maybe we could also add a channel for ThaumatoAnakalyptor

**Comment by schillij95** [comment]
Should be fixed now
